stages:
  - build
  - deploy

build-job:
  stage: build
  image:
    name: harbor.eds.aphp.fr/cohort360/genericbuilder:1.2.0
  script:
    - env
    - curl -LO https://services.gradle.org/distributions/gradle-8.0.2-bin.zip
    - unzip gradle-8.0.2-bin.zip
    - curl https://plugins.gradle.org:443/m2/com/github/node-gradle/node/com.github.node-gradle.node.gradle.plugin/maven-metadata.xml -o maven-metadata.xml
    - cat maven-metadata.xml
    - HOST_PROXY="$HOST_PROXY"
    - PORT_PROXY="$PORT_PROXY"
    - ./gradle-8.0.2/bin/gradle --debug -Dhttps.proxyHost=$HOST_PROXY -Dhttps.proxyPort=$PORT_PROXY buildIG
#    - ./gradlew buildIG
    - echo "VERSION=$(grep -oPm2 "(?<=version:\ )\\d+\\.\\d+\\.\\d+.*$" sushi-config.yaml)" >> build.env
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - output

deploy-job:
  image: harbor.eds.aphp.fr/cohort360/kaniko:debug
  stage: deploy
  needs:
    -   job: build-job
        artifacts: true
  dependencies:
    - build-job
  script:
    - echo $VERSION
    - mkdir -p /kaniko/.docker
    - |-
      KANIKOCFG="{ \"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${BOT_NAME}\",\"password\":\"${BOT_TOKEN}\"}} }"
      echo "${KANIKOCFG}" > /kaniko/.docker/config.json
      /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile --destination ${CI_REGISTRY_IMAGE}:${VERSION}
