id: aphp.fhir.fr.eds
canonical: https://aphp.fr/fhir/fr/eds
name: APHPEntrepotDonneesSante
title: Guide d'implémentation de l'EDS de l'AP-HP
description: Le guide d'implémentation de l'Assistance Publique - Hôpitaux de Paris pour l'Entrepôt de Données de Santé
status: draft
version: 0.0.1
jurisdiction: urn:iso:std:iso:250#FR "France"
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: ci-build
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
publisher:
  name: AP-HP
  url: https://aphp.fr
  # email: test@example.org

dependencies:
    hl7.fhir.fr.core: 1.1.0

pages:
   index.md:
     title: Accueil
   context.md:
     title: Contexte
   profiles.md:
     title: Profils
   extensions.md:
     title: Extensions
   valuesets.md:
     title: Jeux de valeur
   codesystems.md:
     title: Systèmes de code
   change_log.md:
     title: Notes de version
   downloads.md:
     title: Télécharger les spécifications
   glossary.md:
     title: Glossaire

menu:
  Accueil: index.html
  Spécifications EDS:
    Contexte: context.html
  Artefacts FHIR:
    Profils: profiles.html
    Extensions: extensions.html
    Jeux de valeur: valuesets.html
    Systèmes de code: codesystems.html
    Liste complète: artifacts.html
  Notes de version: change_log.html
  Plus:
    Télécharger spécifications: downloads.html